name: CI - Docs

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - "**"
      - "!gh-pages"

env:
  UV_FROZEN: "1"

jobs:
  build-docs:
    uses: ./.github/workflows/generate-docs.yml
    with:
      deploy: false
